### ISSUE TITLE
Implement tower dock

### ISSUE THREAD

**Issue by sam-mata** [toru-studio/COOP#17]
The most basic UI element, the tower dock should hold icons for each tower. If available for purchase, these icons should be draggable onto the map for placement. As this will involve the tower system, @nathanbridgeearney will also be involved.

***Example dock from Bloons TD 2 (pictured far right):***
![image](https://github.com/toru-studio/COOP/assets/49130157/f6b73264-9c6e-4b83-ac01-8de6e5a510f9)

This dock should also be the base for the live counters of #16.
> [!NOTE]
> This issue is reliant on the relevant assets from Holly being completed first.

**Comment by Ofthemasses** [comment]
Could you make the menu pop up on mouseover? Then I can add some SFX for it
![MouseOverExample](https://github.com/toru-studio/COOP/assets/43369124/85833eed-16ad-44cc-b954-04ae1dc17c70)

**Comment by sam-mata** [comment]
@Ofthemasses Will have a look at it!
